//! Generate sssd, krb5, ganesha and export fragments.

use std::fs;
use std::path::Path;

use crate::ignored_attributes;

use crate::{
    constants, sssd_resolver_inputs, ConfigError, GenerationPaths, NfsKlldapConfig,
};
use nfs_klldap_identity::{
    effective_ldap_search_bases, resolve_posix_attribute_mapping, PosixAttributeMapping,
};

mod directives;
mod fragments;

pub(crate) use directives::fragment_basename;
pub use fragments::write_export_fragments;





pub fn generate_all(cfg: &NfsKlldapConfig, paths: &GenerationPaths) -> Result<(), ConfigError> {
    fs::create_dir_all(&paths.exports_dir)?;
    write_sssd_conf(cfg, &paths.sssd_conf)?;
    write_krb5_conf(cfg, &paths.krb5_conf)?;
    write_idmap_conf(cfg, &paths.idmap_conf)?;
    write_nfs_conf(&paths.nfs_conf)?;
    write_export_fragments(cfg, &paths.exports_dir)?;
    write_ganesha_main(cfg, &paths.ganesha_conf, &paths.exports_dir)?;
    Ok(())
}

fn write_sssd_conf(cfg: &NfsKlldapConfig, out: &Path) -> Result<(), ConfigError> {
    let realm = cfg.effective_realm();
    let search_base = cfg
        .sssd
        .ldap_search_base
        .clone()
        .filter(|v| !v.trim().is_empty())
        .unwrap_or_else(|| format!("dc={}", realm.to_lowercase().replace('.', ",dc=")));

    let inputs = sssd_resolver_inputs(&cfg.ldap_uri, &cfg.sssd, &realm);
    let mapping = resolve_posix_attribute_mapping(&inputs.posix_mapping);
    let (user_base, group_base) = effective_ldap_search_bases(&inputs.search_bases, &realm);

    let domain_name = cfg
        .sssd
        .domain
        .clone()
        .filter(|v| !v.trim().is_empty())
        .unwrap_or_else(|| "default".to_string());

    let is_plain_ldap = cfg.ldap_uri.starts_with("ldap:// ");
    let auth_provider = cfg
        .sssd
        .auth_provider
        .clone()
        .filter(|v| !v.trim().is_empty())
        .unwrap_or_else(|| "ldap".to_string());

    let enumerate = cfg.sssd.enumerate.unwrap_or(false);

    let header = format!(
        r#"# GENERATED by nfs-klldap-config — do not edit (source: nfs-klldap.conf)
# Realm: {realm} | domain: {domain} | auth: {auth} | enumerate: {enumerate}

"#,
        realm = realm,
        domain = domain_name,
        auth = auth_provider,
        enumerate = enumerate,
    );

    let mut content = header;
    content.push_str(&format!(
        r#"[sssd]
config_file_version = 2
services = nss, pam
domains = {domain_name}

[nss]
filter_users = root
filter_groups = root

[domain/{domain_name}]
id_provider = ldap
auth_provider = {auth_provider}
ldap_uri = {ldap_uri}
ldap_search_base = {search_base}
ldap_default_bind_dn = {bind_dn}
ldap_default_authtok = {bind_pw}
cache_credentials = true
# SSSD entry cache timeouts from nfs-klldap.conf (defaults below)
entry_cache_timeout = {entry_cache_timeout}
entry_negative_timeout = {entry_negative_timeout}
"#,
        domain_name = domain_name,
        auth_provider = auth_provider,
        ldap_uri = cfg.ldap_uri,
        search_base = search_base,
        bind_dn = cfg.sssd.ldap_default_bind_dn,
        bind_pw = cfg.sssd.ldap_default_authtok,
        entry_cache_timeout = cfg.sssd.entry_cache_timeout.unwrap_or(3600),
        entry_negative_timeout = cfg.sssd.entry_negative_timeout.unwrap_or(60),
    ));

    content.push_str(&build_ldap_domain_options(
        cfg,
        &user_base,
        &group_base,
        is_plain_ldap,
        &mapping,
    ));

    fs::write(out, content.as_bytes())?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(out, fs::Permissions::from_mode(0o600))?;
    }
    Ok(())
}

fn build_ldap_domain_options(
    cfg: &NfsKlldapConfig,
    user_base: &str,
    group_base: &str,
    is_plain_ldap: bool,
    mapping: &PosixAttributeMapping,
) -> String {
    let s = &cfg.sssd;
    let user_attr_list = {
        let mut a = vec![
            mapping.user_name.as_str(),
            mapping.user_uid_number.as_str(),
            mapping.user_gid_number.as_str(),
            mapping.user_home_directory.as_str(),
            mapping.user_shell.as_str(),
            "objectClass",
        ];
        if let Some(f) = s
            .ldap_user_fullname
            .as_ref()
            .filter(|v| !v.trim().is_empty())
        {
            let f = f.trim();
            if !a.iter().any(|x| x.eq_ignore_ascii_case(f)) {
                a.push(f);
            }
        }
        a.join(",")
    };
    let group_attr_list = {
        let a = [
            mapping.group_name.as_str(),
            mapping.group_gid_number.as_str(),
            mapping.group_member.as_str(),
            "objectClass",
        ];
        a.join(",")
    };

    let enumerate = if s.enumerate.unwrap_or(false) {
        "true"
    } else {
        "false"
    };

    let ldap_schema = s
        .ldap_schema
        .as_ref()
        .filter(|v| !v.trim().is_empty())
        .map(|v| v.trim().to_string())
        .unwrap_or_else(|| "rfc2307bis".to_string());

    let auth_provider = s
        .auth_provider
        .as_ref()
        .filter(|v| !v.trim().is_empty())
        .map(|v| v.trim().to_string())
        .unwrap_or_else(|| "ldap".to_string());

    let mut out = format!(
        r#"ldap_user_search_base = {user_base}
ldap_user_search_scope = sub
ldap_user_object_class = {user_obj}
ldap_user_name = {u_name}
ldap_user_uid_number = {u_uid}
ldap_user_gid_number = {u_gid}
ldap_user_home_directory = {u_home}
ldap_user_shell = {u_shell}

ldap_group_search_base = {group_base}
ldap_group_search_scope = sub
ldap_group_object_class = {group_obj}
ldap_group_name = {g_name}
ldap_group_gid_number = {g_gid}
# For KLLDAP + rfc2307bis we recommend "member" (DNs) or "uniqueMember\"
# Defaults to "member" when kllldap_ignored_attributes is active.
ldap_group_member = {g_member}

ldap_schema = {ldap_schema}
ldap_pwd_policy = none
ldap_id_mapping = false
enumerate = {enumerate}
access_provider = {access}"#,
        user_base = user_base,
        user_obj = mapping.user_object_class,
        u_name = mapping.user_name,
        u_uid = mapping.user_uid_number,
        u_gid = mapping.user_gid_number,
        u_home = mapping.user_home_directory,
        u_shell = mapping.user_shell,
        group_base = group_base,
        group_obj = mapping.group_object_class,
        g_name = mapping.group_name,
        g_gid = mapping.group_gid_number,
        g_member = mapping.group_member,
        ldap_schema = ldap_schema,
        enumerate = enumerate,
        access = s
            .access_provider
            .as_deref()
            .filter(|v| !v.trim().is_empty())
            .unwrap_or("permit"),
    );


    out.push_str(&format!(
        "
# Informational (computed from active POSIX attribute mappings above):
# ldap_user_extra_attrs only *adds* (it does not restrict).
# Shown for reference/debugging only:
#ldap_user_attributes = {}
#ldap_group_attributes = {}",
        user_attr_list, group_attr_list
    ));

    if auth_provider == "krb5" {
        out.push_str("\nchpass_provider = krb5");
        if s.krb5_validate.is_none() {
            out.push_str("\nkrb5_validate = false");
        }
    }

    let kdc_host = crate::extract_host_from_uri(&cfg.ldap_uri);
    let realm = cfg.effective_realm();

    out.push_str(&format!("\nkrb5_realm = {}", realm));

    let krb5_server_val = s
        .krb5_server
        .as_ref()
        .filter(|v| !v.trim().is_empty())
        .map(|v| v.trim().to_string())
        .unwrap_or_else(|| kdc_host.clone());

    out.push_str(&format!("\nkrb5_server = {}", krb5_server_val));

    let krb5_kpasswd_val = s
        .krb5_kpasswd
        .as_ref()
        .filter(|v| !v.trim().is_empty())
        .map(|v| v.trim().to_string())
        .unwrap_or_else(|| kdc_host.clone());
    out.push_str(&format!(
        "\nkrb5_kpasswd = {}", krb5_kpasswd_val));

    if let Some(v) = &s.ldap_tls_reqcert {
        if !v.trim().is_empty() {
            out.push_str(&format!(
                "\nldap_tls_reqcert = {}", v.trim()));
        }
    }
    if let Some(v) = &s.ldap_tls_cacert {
        if !v.trim().is_empty() {
            out.push_str(&format!(
                "\nldap_tls_cacert = {}", v.trim()));
        }
    }
    if let Some(v) = s.ldap_id_use_start_tls {
        out.push_str(&format!(
            "\nldap_id_use_start_tls = {}",
            if v { "true" } else { "false" }
        ));
    }
    if let Some(v) = s
        .ldap_user_fullname
        .as_ref()
        .filter(|v| !v.trim().is_empty())
    {
        out.push_str(&format!(
            "\nldap_user_fullname = {}", v.trim()));
    }

    if let Some(v) = s.krb5_validate {
        out.push_str(&format!(
            "\nkrb5_validate = {}",
            if v { "true" } else { "false" }
        ));
    }
    if let Some(v) = s.krb5_store_password_if_offline {
        out.push_str(&format!(
            "\nkrb5_store_password_if_offline = {}",
            if v { "true" } else { "false" }
        ));
    }

    if is_plain_ldap
        && s.ldap_auth_disable_tls_never_use_in_production
            .unwrap_or(true)
    {
        out.push_str("\nldap_auth_disable_tls_never_use_in_production = true");
    }


    let emit_ignores = s.kllldap_ignored_attributes.unwrap_or(true);
    if emit_ignores {
        out.push('\n');
        out.push_str(&ignored_attributes::get_kllldap_ignored_attributes_comment_block());
    }

    out
}

fn write_krb5_conf(cfg: &NfsKlldapConfig, out: &Path) -> Result<(), ConfigError> { 
    let realm = cfg.effective_realm();
    let kdc_host = crate::extract_host_from_uri(&cfg.ldap_uri);

    let content = format!(
        r#"[libdefaults]
    default_realm = {realm}
    dns_lookup_realm = false
    dns_lookup_kdc = false
    rdns = false
    ticket_lifetime = 24h
    renew_lifetime = 7d
    forwardable = true

[realms]
    {realm} = {{
        kdc = {kdc_host}
        admin_server = {kdc_host}
    }}

[domain_realm]
    .{realm_lower} = {realm}
    {realm_lower} = {realm}
"#,
        realm = realm,
        realm_lower = realm.to_lowercase(),
        kdc_host = kdc_host,
    );

    fs::write(out, content.as_bytes())?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let _ = fs::set_permissions(out, fs::Permissions::from_mode(0o644));
    }
    Ok(())
}

/// Write /etc/nfs.conf with use-machine-creds=0 for krb5p user TGT clients.
fn write_nfs_conf(out: &Path) -> Result<(), ConfigError> {
    let content = r#"# GENERATED by nfs-klldap-config — do not edit (source: nfs-klldap.conf)
[general]
pipefs-directory=/run/rpc_pipefs

[gssd]
use-machine-creds=0
"#;
    fs::write(out, content.as_bytes())?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let _ = fs::set_permissions(out, fs::Permissions::from_mode(0o644));
    }
    Ok(())
}

/// Writes /etc/idmapd.conf with Domain from effective_realm and GSS nsswitch.
fn write_idmap_conf(cfg: &NfsKlldapConfig, out: &Path) -> Result<(), ConfigError> {
    let realm = cfg.nfsv4_domain();

    let content = format!(
        r#"# GENERATED by nfs-klldap-config — do not edit (source: nfs-klldap.conf)
# Routes user@REALM via nsswitch + getpwnam (nss_wrapper/sssd) for krb5*.

[General]
Verbosity = 0
Domain = {realm}
Local-Realms = {realm}

[Mapping]
Nobody-User = {nobody_u}
Nobody-Group = {nobody_g}

[Translation]
Method = {method}
GSS-Methods = {gss}
# krb5/krb5p/krb5i: nsswitch + UseGetpwnam=true (getpwuid_r + getgrouplist LogInfo); see ganesha-ctl id-resolve
"#,
        realm = realm,
        nobody_u = constants::IDMAPD_NOBODY_USER,
        nobody_g = constants::IDMAPD_NOBODY_GROUP,
        method = constants::IDMAPD_TRANSLATION_METHOD,
        gss = constants::IDMAPD_GSS_METHODS,
    );

    fs::write(out, content.as_bytes())?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let _ = fs::set_permissions(out, fs::Permissions::from_mode(0o644));
    }
    Ok(())
}

fn ganesha_debug_enabled() -> bool {
    std::env::var("GANESHA_DEBUG")
        .map(|v| {
            matches!(
                v.trim().to_ascii_lowercase().as_str(),
                "true" | "1" | "yes" | "on"
            )
        })
        .unwrap_or(false)
}

fn write_ganesha_main(
    cfg: &NfsKlldapConfig,
    out: &Path,
    exports_dir: &Path,
) -> Result<(), ConfigError> {
    let sec = &cfg.ganesha.default_security;
    let realm = cfg.nfsv4_domain();

    let includes: String = cfg
        .shares
        .iter()
        .enumerate()
        .map(|(i, s)| {
            let name = fragment_basename(i, &s.name);
            format!("%include {}/{}\n", exports_dir.display(), name)
        })
        .collect();

    let rpc_cred_fallback = cfg
        .ganesha
        .enable_rpc_cred_fallback
        .unwrap_or(true);
    let rpc_cred_line = if rpc_cred_fallback {
        "    enable_rpc_cred_fallback = true;  # RPC token gids when uid2grp fails; may mask incomplete nss_wrapper membership.\n"
    } else {
        "    enable_rpc_cred_fallback = false;  # fail closed on uid2grp miss (idhelper authoritative).\n"
    };
    let idmap_validity = cfg
        .ganesha
        .idmapped_validity_secs
        .unwrap_or(constants::GANESHA_IDMAPPED_VALIDITY_SECS);

    let mut content = format!(
        r#"NFS_CORE_PARAM {{
    Protocols = {proto};
    Enable_UDP = false;
    Bind_addr = 0.0.0.0;
    NFS_Port = 2049;
    Enable_RQUOTA = false;
    Enable_NLM = false;
    Allow_Set_Io_Flusher_Fail = true;
{rpc_cred_line}}}

DIRECTORY_SERVICES {{
    DomainName = {realm};
    Pwnam_Implementation = {pwnam};
    Pwutils_Use_Fully_Qualified_Names = true;  # principal2uid uses user@ form; getgrouplist uses passwd login from getpwuid_r.
    Root_Kerberos_Principal = {root_krb};
    # Idmapped_* negative cache TTL (seconds); lower reduces miss stickiness, increases NSS load.
    Idmapped_User_Time_Validity = {idmap_validity};
    Idmapped_Group_Time_Validity = {idmap_validity};
}}

NFS_KRB5 {{
    PrincipalName = "nfs";
    KeytabPath = "/etc/krb5.keytab";
    Active_krb5 = TRUE;
}}

NFSV4 {{
    Only_Numeric_Owners = true;
    Allow_Numeric_Owners = true;
    UseGetpwnam = true;
    RecoveryBackend = fs;
    Lease_Lifetime = 60;
    Grace_Period = 45;
}}

EXPORT_DEFAULTS {{
    SecType = {sec};
    Protocols = {proto};
}}
"#,
        realm = realm,
        sec = sec,
        proto = constants::GANESHA_PROTOCOLS,
        pwnam = constants::GANESHA_PWNAM_IMPL,
        root_krb = constants::GANESHA_ROOT_KRB_PRINCIPALS,
        idmap_validity = idmap_validity,
        rpc_cred_line = rpc_cred_line,
    );

    if ganesha_debug_enabled() {
        content.push_str(
            r#"LOG {
    Default_Log_Level = DEBUG;
    Components {
        CLIENTID = FULL_DEBUG;
        SESSIONS = FULL_DEBUG;
        IDMAPPER = FULL_DEBUG;
        NFS4 = DEBUG;
        DISPATCH = DEBUG;
        XPRT = DEBUG;
    }
}

"#,
        );
    } else {
        content.push_str(
            r#"LOG {
    Default_Log_Level = INFO;
    Components {
        CLIENTID = EVENT;
        SESSIONS = EVENT;
        IDMAPPER = EVENT;
        XPRT = EVENT;
    }
}

"#,
        );
    }

    content.push_str(&includes);

    fs::write(out, content.as_bytes())?;
    Ok(())
}
