//! Generate sssd.conf, krb5.conf, ganesha.conf and per-share export fragments.

use std::fs;
use std::path::Path;

use crate::ignored_attributes;

use crate::{
    config::resolve_posix_attribute_mapping, constants, ConfigError, GenerationPaths, NfsKlldapConfig,
};


pub(crate) fn sanitize_name(s: &str) -> String {
    s.chars()
        .map(|c| {
            if c.is_alphanumeric() || c == '-' || c == '_' {
                c
            } else {
                '-'
            }
        })
        .collect()
}

pub(crate) fn derive_export_id(name: &str, base: u16) -> u16 {
    let mut h: u32 = 0x811c9dc5;
    for b in name.as_bytes() {
        h = h.wrapping_mul(16777619) ^ (*b as u32);
    }
    base + (h % 55000) as u16
}

/// Basename for a managed export fragment (matches write_export_fragments numbering).
pub(crate) fn fragment_basename(index: usize, name: &str) -> String {
    format!("{:02}-{}.conf", index + 10, sanitize_name(name))
}



pub fn generate_all(cfg: &NfsKlldapConfig, paths: &GenerationPaths) -> Result<(), ConfigError> {
    fs::create_dir_all(&paths.exports_dir)?;
    write_sssd_conf(cfg, &paths.sssd_conf)?;
    write_krb5_conf(cfg, &paths.krb5_conf)?;
    // idmapd.conf is independent of ganesha fragments but follows the same realm/sssd
    // info so Domain is consistent for the idhelper + nfsidmap shim + ganesha default.
    write_idmap_conf(cfg, &paths.idmap_conf)?;
    // Fragments first so the referenced files exist when Ganesha parses the main conf.
    write_export_fragments(cfg, &paths.exports_dir)?;
    write_ganesha_main(cfg, &paths.ganesha_conf, &paths.exports_dir)?;
    Ok(())
}

fn write_sssd_conf(cfg: &NfsKlldapConfig, out: &Path) -> Result<(), ConfigError> {
    let realm = cfg.effective_realm();
    let search_base = cfg
        .sssd
        .ldap_search_base
        .clone()
        .filter(|v| !v.trim().is_empty())
        .unwrap_or_else(|| format!("dc={}", realm.to_lowercase().replace('.', ",dc=")));

    let (user_base, group_base) = crate::config::effective_ldap_search_bases(&cfg.sssd, &realm);

    let domain_name = cfg
        .sssd
        .domain
        .clone()
        .filter(|v| !v.trim().is_empty())
        .unwrap_or_else(|| "default".to_string());

    let is_plain_ldap = cfg.ldap_uri.starts_with("ldap://");

    let auth_provider = cfg
        .sssd
        .auth_provider
        .clone()
        .filter(|v| !v.trim().is_empty())
        .unwrap_or_else(|| "ldap".to_string());

    let mapping = resolve_posix_attribute_mapping(&cfg.sssd);
    let enumerate = cfg.sssd.enumerate.unwrap_or(false);
    let kllldap_ignores = cfg.sssd.kllldap_ignored_attributes.unwrap_or(true);

    // Header emitted into generated sssd.conf (user-editable source is nfs-klldap.conf).
    let header = format!(
        r#"# =============================================================================
# GENERATED by nfs-klldap-config — do not edit by hand.
# Source: nfs-klldap.conf (edit that file; watcher/SIGHUP regenerates this).
# Realm: {realm} | domain: {domain} | auth_provider: {auth}
# Defaults [sssd]: ldap_schema=rfc2307bis, ldap_id_mapping=false, enumerate={enumerate},
# ldap_group_member={member}, access_provider=permit, ldap_pwd_policy=none
# kllldap_ignored_attributes={ignores}
#
# Kerberos (co-located KDC): krb5_realm + krb5_server + krb5_kpasswd are
# auto-derived from ldap_uri host (different protocol) + effective realm.
# This is the "kerberos format" counterpart to the auto ldap_ values.
# Ganesha krb5* security (krb5p default) works with default auth_provider=ldap
# (sufficient for id resolution); the krb5_* lines make the domain aware.
# Explicit krb5_server/krb5_kpasswd in [sssd] override the derived values.
#
# ldaps:// without ldap_tls_reqcert: uses system/OpenLDAP TLS defaults — for
#   self-signed LLDAP/KLLDAP set ldap_tls_reqcert = "never" in nfs-klldap.conf.
# =============================================================================

"#,
        realm = realm,
        domain = domain_name,
        auth = auth_provider,
        enumerate = enumerate,
        member = mapping.group_member,
        ignores = kllldap_ignores,
    );

    let mut content = header;
    content.push_str(&format!(
        r#"[sssd]
config_file_version = 2
services = nss, pam
domains = {domain_name}

[nss]
filter_users = root
filter_groups = root

[domain/{domain_name}]
id_provider = ldap
auth_provider = {auth_provider}
ldap_uri = {ldap_uri}
ldap_search_base = {search_base}
ldap_default_bind_dn = {bind_dn}
ldap_default_authtok = {bind_pw}
cache_credentials = true
# Ample ID cache settings (derived from nfs-klldap.conf or defaults) to ensure
# quick getent/SSSD lookups for UID/GID without constantly hitting the LDAP server.
# These are emitted so resolution info from the source conf is utilized for performance.
entry_cache_timeout = {entry_cache_timeout}
entry_negative_timeout = {entry_negative_timeout}
"#,
        domain_name = domain_name,
        auth_provider = auth_provider,
        ldap_uri = cfg.ldap_uri,
        search_base = search_base,
        bind_dn = cfg.sssd.ldap_default_bind_dn,
        bind_pw = cfg.sssd.ldap_default_authtok,
        entry_cache_timeout = cfg.sssd.entry_cache_timeout.unwrap_or(3600),
        entry_negative_timeout = cfg.sssd.entry_negative_timeout.unwrap_or(60),
    ));

    content.push_str(&build_ldap_domain_options(
        cfg,
        &user_base,
        &group_base,
        is_plain_ldap,
    ));

    fs::write(out, content.as_bytes())?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(out, fs::Permissions::from_mode(0o600))?;
    }
    Ok(())
}

fn build_ldap_domain_options(
    cfg: &NfsKlldapConfig,
    user_base: &str,
    group_base: &str,
    is_plain_ldap: bool,
) -> String {
    let s = &cfg.sssd;

    let mapping = resolve_posix_attribute_mapping(s);
    let user_attr_list = {
        let mut a = vec![
            mapping.user_name.as_str(),
            mapping.user_uid_number.as_str(),
            mapping.user_gid_number.as_str(),
            mapping.user_home_directory.as_str(),
            mapping.user_shell.as_str(),
            "objectClass",
        ];
        if let Some(f) = s
            .ldap_user_fullname
            .as_ref()
            .filter(|v| !v.trim().is_empty())
        {
            let f = f.trim();
            if !a.iter().any(|x| x.eq_ignore_ascii_case(f)) {
                a.push(f);
            }
        }
        a.join(",")
    };
    let group_attr_list = {
        let a = [
            mapping.group_name.as_str(),
            mapping.group_gid_number.as_str(),
            mapping.group_member.as_str(),
            "objectClass",
        ];
        a.join(",")
    };

    let enumerate = if s.enumerate.unwrap_or(false) {
        "true"
    } else {
        "false"
    };

    let ldap_schema = s
        .ldap_schema
        .as_ref()
        .filter(|v| !v.trim().is_empty())
        .map(|v| v.trim().to_string())
        .unwrap_or_else(|| "rfc2307bis".to_string());

    let auth_provider = s
        .auth_provider
        .as_ref()
        .filter(|v| !v.trim().is_empty())
        .map(|v| v.trim().to_string())
        .unwrap_or_else(|| "ldap".to_string());

    let mut out = format!(
        r#"ldap_user_search_base = {user_base}
ldap_user_search_scope = sub
ldap_user_object_class = {user_obj}
ldap_user_name = {u_name}
ldap_user_uid_number = {u_uid}
ldap_user_gid_number = {u_gid}
ldap_user_home_directory = {u_home}
ldap_user_shell = {u_shell}

ldap_group_search_base = {group_base}
ldap_group_search_scope = sub
ldap_group_object_class = {group_obj}
ldap_group_name = {g_name}
ldap_group_gid_number = {g_gid}
# For KLLDAP + rfc2307bis we recommend "member" (DNs) or "uniqueMember".
# The resolver now defaults to "member" when kllldap_ignored_attributes is active.
ldap_group_member = {g_member}

ldap_schema = {ldap_schema}
ldap_pwd_policy = none
ldap_id_mapping = false
enumerate = {enumerate}
access_provider = {access}"#,
        user_base = user_base,
        user_obj = mapping.user_object_class,
        u_name = mapping.user_name,
        u_uid = mapping.user_uid_number,
        u_gid = mapping.user_gid_number,
        u_home = mapping.user_home_directory,
        u_shell = mapping.user_shell,
        group_base = group_base,
        group_obj = mapping.group_object_class,
        g_name = mapping.group_name,
        g_gid = mapping.group_gid_number,
        g_member = mapping.group_member,
        ldap_schema = ldap_schema,
        enumerate = enumerate,
        access = s
            .access_provider
            .as_deref()
            .filter(|v| !v.trim().is_empty())
            .unwrap_or("permit"),
    );


    out.push_str(&format!(
        "\n# Informational (computed from active POSIX attribute mappings above):\n# ldap_user_extra_attrs only *adds* (it does not restrict).\n# Shown for reference/debugging only:\n#ldap_user_attributes = {}\n#ldap_group_attributes = {}",
        user_attr_list, group_attr_list
    ));

    // krb5 auth: avoid extra LDAP roundtrips.
    if auth_provider == "krb5" {
        out.push_str("\nchpass_provider = krb5");
        // krb5_validate=false avoids extra LDAP lookups for TGT validation
        // in many common LLDAP + krb5 setups.
        if s.krb5_validate.is_none() {
            out.push_str("\nkrb5_validate = false");
        }
    }

    // Auto-derived Kerberos (KDC) settings for the co-located LDAP+KDC case.
    // The host is taken from ldap_uri (different protocol/port than LDAP) and
    // the realm matches the rest of the stack (kerberos.realm / effective_realm).
    // This gives the sssd [domain] the "kerberos format" equivalent of the
    // auto-derived ldap values. Explicit [sssd] krb5_* values override.
    // Ganesha krb5* SecType (krb5p default) still works with auth_provider=ldap
    // (the default); these lines make the domain properly Kerberos-aware for
    // resolution alongside the idhelper.
    let kdc_host = crate::extract_host_from_uri(&cfg.ldap_uri);
    let realm = cfg.effective_realm();  // safe: called after validate_and_derive

    // krb5_realm: always the effective realm (same as kerberos.realm and krb5.conf).
    // No separate override field needed in this design (realm is single source).
    out.push_str(&format!("\nkrb5_realm = {}", realm));

    let krb5_server_val = s
        .krb5_server
        .as_ref()
        .filter(|v| !v.trim().is_empty())
        .map(|v| v.trim().to_string())
        .unwrap_or_else(|| kdc_host.clone());

    out.push_str(&format!("\nkrb5_server = {}", krb5_server_val));

    // kpasswd: auto to same host (common for co-located) unless explicitly set
    let krb5_kpasswd_val = s
        .krb5_kpasswd
        .as_ref()
        .filter(|v| !v.trim().is_empty())
        .map(|v| v.trim().to_string())
        .unwrap_or_else(|| kdc_host.clone());
    out.push_str(&format!("\nkrb5_kpasswd = {}", krb5_kpasswd_val));

    // Optional fields — only emit when explicitly set
    if let Some(v) = &s.ldap_tls_reqcert {
        if !v.trim().is_empty() {
            out.push_str(&format!("\nldap_tls_reqcert = {}", v.trim()));
        }
    }
    if let Some(v) = &s.ldap_tls_cacert {
        if !v.trim().is_empty() {
            out.push_str(&format!("\nldap_tls_cacert = {}", v.trim()));
        }
    }
    if let Some(v) = s.ldap_id_use_start_tls {
        out.push_str(&format!(
            "\nldap_id_use_start_tls = {}",
            if v { "true" } else { "false" }
        ));
    }
    if let Some(v) = s
        .ldap_user_fullname
        .as_ref()
        .filter(|v| !v.trim().is_empty())
    {
        out.push_str(&format!("\nldap_user_fullname = {}", v.trim()));
    }

    // Advanced krb5 knobs (krb5_server/krb5_kpasswd emitted above with auto-derived defaults)
    if let Some(v) = s.krb5_validate {
        out.push_str(&format!(
            "\nkrb5_validate = {}",
            if v { "true" } else { "false" }
        ));
    }
    if let Some(v) = s.krb5_store_password_if_offline {
        out.push_str(&format!(
            "\nkrb5_store_password_if_offline = {}",
            if v { "true" } else { "false" }
        ));
    }

    // Plain ldap:// safety flag
    if is_plain_ldap
        && s.ldap_auth_disable_tls_never_use_in_production
            .unwrap_or(true)
    {
        out.push_str("\nldap_auth_disable_tls_never_use_in_production = true");
    }


    let emit_ignores = s.kllldap_ignored_attributes.unwrap_or(true);
    if emit_ignores {
        out.push_str("\n\n");
        out.push_str(&ignored_attributes::get_kllldap_ignored_attributes_comment_block());
    }

    out
}

fn write_krb5_conf(cfg: &NfsKlldapConfig, out: &Path) -> Result<(), ConfigError> {
    let realm = cfg.effective_realm();
    let kdc_host = crate::extract_host_from_uri(&cfg.ldap_uri);

    let content = format!(
        r#"[libdefaults]
    default_realm = {realm}
    dns_lookup_realm = false
    dns_lookup_kdc = false
    rdns = false
    ticket_lifetime = 24h
    renew_lifetime = 7d
    forwardable = true

[realms]
    {realm} = {{
        kdc = {kdc_host}
        admin_server = {kdc_host}
    }}

[domain_realm]
    .{realm_lower} = {realm}
    {realm_lower} = {realm}
"#,
        realm = realm,
        realm_lower = realm.to_lowercase(),
        kdc_host = kdc_host,
    );

    fs::write(out, content.as_bytes())?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let _ = fs::set_permissions(out, fs::Permissions::from_mode(0o644));
    }
    Ok(())
}

/// Write a standardized /etc/idmapd.conf (or equivalent path) driven by the central
/// nfs-klldap.conf. Domain + Local-Realms taken from effective_realm() (same source as
/// ganesha DIRECTORY_SERVICES.DomainName and krb5 default_realm). Method = nsswitch
/// (plus explicit GSS-Methods) because we use direct POSIX (ldap_id_mapping=false in
/// generated sssd) + our idhelper for Kerberos principals (user TGTs + machine
/// host/nfs/ principals from client host keytabs). Consistent Domain/Local-Realms +
/// nsswitch/GSS-Methods for Ganesha 9.6 trixie + libnfsidmap fallback + client rpc.idmapd.
/// No Idmap* keys are ever emitted into ganesha.conf (deprecated for 9.x).
fn write_idmap_conf(cfg: &NfsKlldapConfig, out: &Path) -> Result<(), ConfigError> {
    let realm = cfg.effective_realm();

    let content = format!(
        r#"# =============================================================================
# GENERATED by nfs-klldap-config — do not edit by hand.
# Source: nfs-klldap.conf (edit that file; watcher/SIGHUP regenerates this).
# Follows [kerberos] realm + [sssd] configuration (posix attrs, search bases,
# ldap_id_mapping=false, entry caches, nsswitch path) for full stack consistency.
# Provides the NFSv4 Domain expected by Ganesha 9.6 IDMAPPER (default IdmapConf),
# the nfsidmap-idhelper shim (for "using nfsidmap" principal resolution), and
# client rpc.idmapd (Method=sss or nsswitch). The nfs-klldap-idhelper remains
# authoritative for machine vs user principal classification and uid/gid materialization.
#
# Kerberos hybrid (user TGT + machine principals) notes (Ganesha 9.6 / trixie):
# - Local-Realms tells libnfsidmap/nfsidmap that @REALM principals belong to our
#   NFSv4 domain (so "alice@REALM" and "host/client@REALM" are not treated as
#   foreign-domain and dropped to nobody).
# - GSS-Methods covers the GSS-authenticated name path used for Kerberos creds.
# - Actual uid/gid decisions (especially host/...@REALM -> 0:0) live in the
#   idhelper + nss_wrapper/extrausers materialization + Pwnam_Implementation=nsswitch.
# =============================================================================

[General]
Verbosity = 0
Domain = {realm}
Local-Realms = {realm}

[Mapping]
Nobody-User = {nobody_u}
Nobody-Group = {nobody_g}

[Translation]
Method = {method}
GSS-Methods = {gss}
"#,
        realm = realm,
        nobody_u = constants::IDMAPD_NOBODY_USER,
        nobody_g = constants::IDMAPD_NOBODY_GROUP,
        method = constants::IDMAPD_TRANSLATION_METHOD,
        gss = constants::IDMAPD_GSS_METHODS,
    );

    fs::write(out, content.as_bytes())?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let _ = fs::set_permissions(out, fs::Permissions::from_mode(0o644));
    }
    Ok(())
}

fn ganesha_debug_enabled() -> bool {
    std::env::var("GANESHA_DEBUG")
        .map(|v| v.trim() == "TRUE")
        .unwrap_or(false)
}

fn write_ganesha_main(
    cfg: &NfsKlldapConfig,
    out: &Path,
    exports_dir: &Path,
) -> Result<(), ConfigError> {
    let sec = &cfg.ganesha.default_security;
    let realm = cfg.effective_realm();

    // Explicit includes (no glob) for deterministic load order and to avoid
    // Ganesha startup races on container restart / image rebuild.
    let includes: String = cfg
        .shares
        .iter()
        .enumerate()
        .map(|(i, s)| {
            let name = fragment_basename(i, &s.name);
            format!("%include {}/{}\n", exports_dir.display(), name)
        })
        .collect();

    let mut content = format!(
        r#"NFS_CORE_PARAM {{
    Protocols = {proto};
    Bind_addr = 0.0.0.0;
    NFS_Port = 2049;
    # Enable_UDP = false;
    Enable_RQUOTA = false;
    Enable_NLM = false;
    Allow_Set_Io_Flusher_Fail = true;
    Manage_Gids_Expiration = 600;
}}

DIRECTORY_SERVICES {{
    DomainName = {realm};
    Pwnam_Implementation = {pwnam};
    # Ganesha 9.6 trixie only. idhelper (not this file) owns principal->uid classification.
    Root_Kerberos_Principal = {root_krb};
}}

NFS_KRB5 {{
    PrincipalName = "nfs";
    KeytabPath = "/etc/krb5.keytab";
    Active_krb5 = TRUE;
}}

NFSV4 {{
    Allow_Numeric_Owners = false;
    RecoveryBackend = fs;
    Lease_Lifetime = 20;
    Grace_Period = 20;
}}

EXPORT_DEFAULTS {{
    SecType = {sec};
    Protocols = {proto};
    # Read_Access_Check_Policy intentionally omitted from EXPORT_DEFAULTS.
    # Default is "pre" (per ganesha-export-config.8 for 9.x). Emitting it here
    # produces "Unknown parameter" on Ganesha 9.6 from trixie-backports.
    # The policy (when desired) is only placed inside CLIENT blocks below.
}}
"#,
        realm = realm,
        sec = sec,
        proto = constants::GANESHA_PROTOCOLS,
        pwnam = constants::GANESHA_PWNAM_IMPL,
        root_krb = constants::GANESHA_ROOT_KRB_PRINCIPALS,
    );

    // Always emit a baseline LOG block with elevated visibility for identity/client
    // related components. This gives the idhelper observer (and operators) a much
    // better chance of seeing client records, session setup, and owner/principal
    // strings during the real authenticated mount phases without requiring the
    // heavy GANESHA_DEBUG=TRUE mode.
    if ganesha_debug_enabled() {
        content.push_str(
            r#"LOG {
    Default_Log_Level = DEBUG;
    Components {
        CLIENTID = FULL_DEBUG;
        SESSIONS = FULL_DEBUG;
        IDMAPPER = FULL_DEBUG;
        RECOVERY = FULL_DEBUG;
        NFS4 = DEBUG;
        DISPATCH = DEBUG;
        XPRT = DEBUG;
    }
}

"#,
        );
    } else {
        content.push_str(
            r#"LOG {
    Default_Log_Level = INFO;
    Components {
        CLIENTID = EVENT;
        SESSIONS = EVENT;
        IDMAPPER = EVENT;
        XPRT = EVENT;
    }
}

"#,
        );
    }

    content.push_str(&includes);

    fs::write(out, content.as_bytes())?;
    Ok(())
}

fn write_export_fragments(cfg: &NfsKlldapConfig, exports_dir: &Path) -> Result<(), ConfigError> {
    // Remove prior managed fragments (we own exports.d/*.conf)
    if exports_dir.exists() {
        for entry in fs::read_dir(exports_dir)? {
            let p = entry?.path();
            if let Some(name) = p.file_name().and_then(|s| s.to_str()) {
                if name.ends_with(".conf") {
                    let _ = fs::remove_file(&p);
                }
            }
        }
    }

    for (i, share) in cfg.shares.iter().enumerate() {
        let export_id = derive_export_id(&share.name, 1000 + (i as u16 * 10));
        let path = cfg.container_path_for(share); // internal (derived from share's host_path first dir + tail)
        let default_pseudo = format!("/{}", share.name);
        let pseudo_raw = share.export_path.as_deref().unwrap_or(&default_pseudo); // external (can differ / be short)
        // Ganesha requires Pseudo to be absolute. validate_and_derive now guarantees it,
        // but keep a cheap defensive absolutize for any direct construction or legacy raw.
        let pseudo = if pseudo_raw.starts_with('/') {
            pseudo_raw.to_string()
        } else {
            format!("/{}", pseudo_raw)
        };
        let default_sec = &cfg.ganesha.default_security;
        let sec = share.security.as_deref().unwrap_or(default_sec);
        let access = if share.rw.unwrap_or(true) { "RW" } else { "RO" };
        let squash = share.squash.as_deref().unwrap_or("no_root_squash");

        // Resolve Pref* from cache_profile or raw pref_* fallback.
        let (pref_r, pref_w) = if let Some(cp) = &share.cache_profile {
            if let Some((r, w)) = crate::resolve_cache_profile(cp) {
                (Some(r), Some(w))
            } else {
                (share.pref_read, share.pref_write)
            }
        } else {
            (share.pref_read, share.pref_write)
        };

        let pref_read_line = pref_r
            .map(|v| format!("    PrefRead = {};\n", v))
            .unwrap_or_default();
        let pref_write_line = pref_w
            .map(|v| format!("    PrefWrite = {};\n", v))
            .unwrap_or_default();

        // CLIENT block: Protocols=4 + explicit Read_Access_Check_Policy=pre.
        // Placed only inside CLIENT (inside EXPORT) for parser compatibility on
        // Ganesha 9.6 Debian trixie-backports (EXPORT_DEFAULTS rejects the key).
        // Additional CLIENT blocks may be appended manually (not preserved on regen).
        let client_block = format!(
            r#"
    CLIENT {{
        Clients = *;
        Access_Type = {access};
        Protocols = 4;
        # Valid for ganesha 9.6 trixie-backports (manpage enum [pre,post,all]).
        Read_Access_Check_Policy = pre;
    }}

"#,
            access = access,
        );

        let block = format!(
            r#"# Generated from nfs-klldap.conf share "{}"
EXPORT {{
    Export_Id = {};
    Path = {};
    Pseudo = {};
    SecType = {};
    Squash = {};
{pref_read_line}{pref_write_line}{client_block}    FSAL {{
        Name = VFS;
    }}
}}
"#,
            share.name, export_id, path, pseudo, sec, squash, pref_read_line = pref_read_line, pref_write_line = pref_write_line, client_block = client_block
        );

        let filename = fragment_basename(i, &share.name);
        fs::write(exports_dir.join(filename), block.as_bytes())?;
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sanitize_name_replaces_invalid_chars() {
        assert_eq!(sanitize_name("my share!"), "my-share-");
        assert_eq!(sanitize_name("data_01"), "data_01");
        assert_eq!(sanitize_name("foo@bar#baz"), "foo-bar-baz");
    }

    #[test]
    fn derive_export_id_is_deterministic() {
        let id1 = derive_export_id("movies", 1000);
        let id2 = derive_export_id("movies", 1000);
        assert_eq!(id1, id2);
        assert_ne!(
            derive_export_id("movies", 1000),
            derive_export_id("data", 1000)
        );
    }

    #[test]
    fn pref_read_emitted_conditionally_in_export_fragment() {
        // Minimal config + share with explicit PrefRead (legacy path)
        let mut cfg = crate::NfsKlldapConfig {
            ldap_uri: "ldaps://k.test:6360".into(),
            sssd: crate::SssdSection {
                ldap_default_bind_dn: "uid=admin,ou=people,dc=test,dc=com".into(),
                ldap_default_authtok: "sekret".into(),
                ..Default::default()
            },
            shares: vec![crate::Share {
                name: "stream".into(),
                host_path: "/media/stream".into(),
                cache_profile: None, // force direct pref_read path (legacy numeric in source)
                pref_read: Some(16 * 1024 * 1024),
                ..Default::default()
            }],
            ..Default::default()
        };
        cfg.validate_and_derive().expect("valid test config");

        let tmp = tempfile::tempdir().unwrap();
        let exports_dir = tmp.path().join("exports.d");
        let paths = crate::GenerationPaths {
            sssd_conf: tmp.path().join("sssd.conf"),
            krb5_conf: tmp.path().join("krb5.conf"),
            ganesha_conf: tmp.path().join("ganesha.conf"),
            exports_dir: exports_dir.clone(),
            idmap_conf: tmp.path().join("idmapd.conf"),
        };
        crate::generate_all(&cfg, &paths).expect("generate");

        let frag_path = exports_dir.join("10-stream.conf");
        let frag = std::fs::read_to_string(&frag_path).unwrap_or_else(|_| {
            // Fallback (name shift tolerance)
            let mut s = String::new();
            if let Ok(rd) = std::fs::read_dir(&exports_dir) {
                for e in rd.flatten() {
                    let p = e.path();
                    if p.to_string_lossy().contains("stream") {
                        s = std::fs::read_to_string(p).unwrap_or_default();
                        break;
                    }
                }
            }
            s
        });
        assert!(
            frag.contains("PrefRead = 16777216;"),
            "expected PrefRead line for streaming share, got:\n{}",
            frag
        );
        assert!(frag.contains("EXPORT {"));
        assert!(frag.contains("Access_Type = RW;"), "CLIENT Access_Type should be RW");
        assert!(frag.contains("CLIENT {"), "CLIENT block should be present");
        assert!(frag.contains("SecType = krb5p;"), "default SecType should appear in EXPORT block");
        assert!(!frag.contains("\n    Access_Type ="), "Access_Type must not be at EXPORT level (4-space indent) anymore");
        assert!(frag.contains("Protocols = 4;"), "CLIENT should explicitly list Protocols = 4 to avoid core/client mismatch warning");
        assert!(frag.contains("Read_Access_Check_Policy = pre;"), "CLIENT must declare Read_Access_Check_Policy = pre (ganesha 9.6 trixie-backports)");
    }

    #[test]
    fn cache_profile_emits_both_pref_read_and_pref_write() {
        // Asymmetric profile (Read-Heavy) to prove both Pref* emitted.
        let mut cfg = crate::NfsKlldapConfig {
            ldap_uri: "ldaps://k.test:6360".into(),
            sssd: crate::SssdSection {
                ldap_default_bind_dn: "uid=admin,ou=people,dc=test,dc=com".into(),
                ldap_default_authtok: "sekret".into(),
                ..Default::default()
            },
            shares: vec![crate::Share {
                name: "movies4k".into(),
                host_path: "/media/movies4k".into(),
                cache_profile: Some("Read - Heavy".to_string()),
                // No raw pref_*; profile supplies.
                ..Default::default()
            }],
            ..Default::default()
        };
        cfg.validate_and_derive().expect("valid test config");

        let tmp = tempfile::tempdir().unwrap();
        let exports_dir = tmp.path().join("exports.d");
        let paths = crate::GenerationPaths {
            sssd_conf: tmp.path().join("sssd.conf"),
            krb5_conf: tmp.path().join("krb5.conf"),
            ganesha_conf: tmp.path().join("ganesha.conf"),
            exports_dir: exports_dir.clone(),
            idmap_conf: tmp.path().join("idmapd.conf"),
        };
        crate::generate_all(&cfg, &paths).expect("generate");

        let frag_path = exports_dir.join("10-movies4k.conf");
        let frag = std::fs::read_to_string(&frag_path).unwrap_or_else(|_| {
            let mut s = String::new();
            if let Ok(rd) = std::fs::read_dir(&exports_dir) {
                for e in rd.flatten() {
                    let p = e.path();
                    if p.to_string_lossy().contains("movies4k") {
                        s = std::fs::read_to_string(p).unwrap_or_default();
                        break;
                    }
                }
            }
            s
        });

        assert!(
            frag.contains("PrefRead = 16777216;"),
            "expected PrefRead from Read-Heavy profile, got:\n{}",
            frag
        );
        assert!(
            frag.contains("PrefWrite = 8388608;"),
            "expected PrefWrite from Read-Heavy profile (asymmetric), got:\n{}",
            frag
        );
        assert!(frag.contains("EXPORT {"));
        assert!(frag.contains("Access_Type = RW;"), "CLIENT Access_Type should be RW");
        assert!(frag.contains("CLIENT {"), "CLIENT block should be present");
        assert!(frag.contains("SecType = krb5p;"), "default SecType should appear in EXPORT block");
        assert!(!frag.contains("\n    Access_Type ="), "Access_Type must not be at EXPORT level (4-space indent) anymore");
        assert!(frag.contains("Protocols = 4;"), "CLIENT should explicitly list Protocols = 4 to avoid core/client mismatch warning");
        assert!(frag.contains("Read_Access_Check_Policy = pre;"), "CLIENT must declare Read_Access_Check_Policy = pre (ganesha 9.6 trixie-backports)");
    }

    #[test]
    fn per_share_export_respects_rw_and_security_overrides() {
        // Exercise non-defaults: RO + krb5i security -> EXPORT must reflect them
        let mut cfg = crate::NfsKlldapConfig {
            ldap_uri: "ldaps://k.test:6360".into(),
            sssd: crate::SssdSection {
                ldap_default_bind_dn: "uid=admin,ou=people,dc=test,dc=com".into(),
                ldap_default_authtok: "sekret".into(),
                ..Default::default()
            },
            shares: vec![crate::Share {
                name: "backups".into(),
                host_path: "/media/backups".into(),
                rw: Some(false),
                security: Some("krb5i".to_string()),
                cache_profile: Some("Default".to_string()),
                ..Default::default()
            }],
            ..Default::default()
        };
        cfg.validate_and_derive().expect("valid test config");

        let tmp = tempfile::tempdir().unwrap();
        let exports_dir = tmp.path().join("exports.d");
        let paths = crate::GenerationPaths {
            sssd_conf: tmp.path().join("sssd.conf"),
            krb5_conf: tmp.path().join("krb5.conf"),
            ganesha_conf: tmp.path().join("ganesha.conf"),
            exports_dir: exports_dir.clone(),
            idmap_conf: tmp.path().join("idmapd.conf"),
        };
        crate::generate_all(&cfg, &paths).expect("generate");

        let frag_path = exports_dir.join("10-backups.conf");
        let frag = std::fs::read_to_string(&frag_path).unwrap_or_else(|_| {
            let mut s = String::new();
            if let Ok(rd) = std::fs::read_dir(&exports_dir) {
                for e in rd.flatten() {
                    if e.path().to_string_lossy().contains("backups") {
                        s = std::fs::read_to_string(e.path()).unwrap_or_default();
                        break;
                    }
                }
            }
            s
        });

        assert!(frag.contains("Access_Type = RO;"), "CLIENT Access_Type should be RO");
        assert!(frag.contains("CLIENT {"), "CLIENT block should be present");
        assert!(frag.contains("SecType = krb5i;"), "EXPORT SecType should be krb5i");
        assert!(!frag.contains("\n    Access_Type ="), "Access_Type must not be at EXPORT level (4-space indent) anymore");
        assert!(frag.contains("Protocols = 4;"), "CLIENT should explicitly list Protocols = 4 to avoid core/client mismatch warning");
        assert!(frag.contains("Read_Access_Check_Policy = pre;"), "CLIENT must declare Read_Access_Check_Policy = pre (ganesha 9.6 trixie-backports)");
    }

    #[test]
    fn idmap_conf_generated_with_domain_from_realm_and_nsswitch() {
        // Verifies standardized idmapd.conf generation follows effective_realm()
        // and [sssd] policy (nsswitch + direct POSIX). No new ganesha.conf keys.
        let mut cfg = crate::NfsKlldapConfig {
            ldap_uri: "ldaps://k.test:6360".into(),
            sssd: crate::SssdSection {
                ldap_default_bind_dn: "uid=admin,ou=people,dc=test,dc=com".into(),
                ldap_default_authtok: "sekret".into(),
                ..Default::default()
            },
            shares: vec![crate::Share {
                name: "data".into(),
                host_path: "/media/data".into(),
                ..Default::default()
            }],
            ..Default::default()
        };
        cfg.validate_and_derive().expect("valid test config");
        assert_eq!(cfg.effective_realm(), "TEST");

        let tmp = tempfile::tempdir().unwrap();
        let exports_dir = tmp.path().join("exports.d");
        let idmap_path = tmp.path().join("idmapd.conf");
        let paths = crate::GenerationPaths {
            sssd_conf: tmp.path().join("sssd.conf"),
            krb5_conf: tmp.path().join("krb5.conf"),
            ganesha_conf: tmp.path().join("ganesha.conf"),
            exports_dir: exports_dir.clone(),
            idmap_conf: idmap_path.clone(),
        };
        crate::generate_all(&cfg, &paths).expect("generate");

        let idmap = std::fs::read_to_string(&idmap_path).expect("idmapd.conf written");
        assert!(idmap.contains("GENERATED by nfs-klldap-config"));
        assert!(idmap.contains("Source: nfs-klldap.conf"));
        assert!(idmap.contains("[sssd]") || idmap.contains("sssd"));
        assert!(idmap.contains("Domain = TEST"));
        assert!(idmap.contains("Local-Realms = TEST"));
        assert!(idmap.contains("Method = nsswitch"));
        assert!(idmap.contains("GSS-Methods = nsswitch"));
        assert!(idmap.contains("Nobody-User = nobody"));
        // Ensure we did not pollute ganesha.conf with idmap keys
        let ganesha = std::fs::read_to_string(&paths.ganesha_conf).unwrap_or_default();
        assert!(!ganesha.contains("IdmapConf"));
        assert!(!ganesha.contains("idmapd.conf"));
        // Read_Access_Check_Policy assignment must be absent from main ganesha.conf (EXPORT_DEFAULTS level)
        // on trixie-backports Ganesha 9.6 (parser rejects it there). It remains only in CLIENT
        // blocks inside the generated export fragments. Match the active assignment form, not comments.
        assert!(!ganesha.contains("Read_Access_Check_Policy ="), "Read_Access_Check_Policy = must not appear in main ganesha.conf (EXPORT_DEFAULTS level)");
    }
}
