//! nfs-klldap-config: TOML validation, derivation, and generation of sssd.conf, krb5.conf, ganesha exports.

mod config;
mod error;
mod generate;
mod hostname;
mod persist;
mod template;
mod uri;
mod validate;

pub use config::{
    effective_ldap_search_bases, resolve_posix_attribute_mapping, GaneshaSection, GenerationPaths,
    KerberosSection, ManagementSection, NfsKlldapConfig, PosixAttributeMapping, ServerSection,
    Share, SssdSection, StorageSection,
};

pub mod ignored_attributes;
pub use error::ConfigError;

pub use generate::generate_all;
pub use hostname::{
    format_nfs_principal_list, get_consistent_hostname, looks_like_docker_default_hostname,
    nfs_keytab_host_matches, nfs_keytab_host_variants, ConsistentHostname, HostnameInconsistency,
    HostnameObservation, HostnameSource,
};
pub use persist::{is_persistent_config, load_host_paths_only};
pub use template::{generate_default_template, write_default_config_if_missing};
pub use uri::{derive_realm_from_uri, extract_host_from_uri};

/// Returns (no_tls_verify, start_tls) derived from [sssd] TLS fields and ldap_uri scheme.
pub fn ldap_tls_policy(
    ldap_uri: &str,
    reqcert: Option<&str>,
    cacert: Option<&str>,
    id_use_start_tls: Option<bool>,
) -> (bool, bool) {
    let has_custom = cacert.is_some_and(|s| !s.trim().is_empty());
    let no_verify = if has_custom {
        reqcert.is_some_and(|v| v.eq_ignore_ascii_case("never"))
    } else if ldap_uri.starts_with("ldaps://") {
        reqcert.is_none_or(|v| v.eq_ignore_ascii_case("never"))
    } else {
        reqcert.is_some_and(|v| v.eq_ignore_ascii_case("never"))
    };
    (no_verify, id_use_start_tls.unwrap_or(false))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    /// Serializes env-mutating tests under `cargo test --workspace`.
    static ENV_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

    /// RAII guard restoring previous env var value on drop.
    struct EnvGuard {
        key: &'static str,
        previous: Option<String>,
    }

    impl EnvGuard {
        fn set(key: &'static str, value: &str) -> Self {
            let previous = std::env::var(key).ok();
            std::env::set_var(key, value);
            Self { key, previous }
        }

        fn remove(key: &'static str) -> Self {
            let previous = std::env::var(key).ok();
            std::env::remove_var(key);
            Self { key, previous }
        }
    }

    impl Drop for EnvGuard {
        fn drop(&mut self) {
            match &self.previous {
                Some(v) => std::env::set_var(self.key, v),
                None => std::env::remove_var(self.key),
            }
        }
    }

    fn minimal_cfg() -> NfsKlldapConfig {
        let mut c = NfsKlldapConfig {
            ldap_uri: "ldaps://kllap.test:6360".into(),
            sssd: SssdSection {
                ldap_default_bind_dn: "uid=admin,ou=people,dc=test,dc=com".into(),
                ldap_default_authtok: "sekret".into(),
                ..Default::default()
            },
            shares: vec![
                Share {
                    name: "movies".into(),
                    host_path: "/media/SSD/movies".into(),
                    ..Default::default()
                },
                Share {
                    name: "data".into(),
                    host_path: "/media/SSD/data".into(),
                    security: Some("krb5i".into()),
                    ..Default::default()
                },
            ],
            ..Default::default()
        };
        c.validate_and_derive().expect("valid minimal");
        c
    }

    #[test]
    fn load_and_derive_works() {
        let c = minimal_cfg();
        assert_eq!(c.effective_realm(), "TEST");
        assert!(c.sssd.port.is_some());
        assert_eq!(c.shares.len(), 2);
        assert_eq!(c.container_path_for(&c.shares[0]), "/export/movies");
    }

    #[test]
    fn generate_produces_expected_artifacts() {
        let cfg = minimal_cfg();
        let tmp = tempfile::tempdir().unwrap();
        let paths = GenerationPaths {
            sssd_conf: tmp.path().join("sssd.conf"),
            krb5_conf: tmp.path().join("krb5.conf"),
            ganesha_conf: tmp.path().join("ganesha.conf"),
            exports_dir: tmp.path().join("exports.d"),
        };
        generate_all(&cfg, &paths).expect("generate");

        let sssd = fs::read_to_string(&paths.sssd_conf).unwrap();
        assert!(sssd.contains("GENERATED by nfs-klldap-config"));
        assert!(sssd.contains("ldap_uri = ldaps://kllap.test:6360"));
        assert!(sssd.contains("ldap_default_authtok = sekret"));
        assert_eq!(
            sssd.matches("ldap_id_mapping = false").count(),
            1,
            "ldap_id_mapping must appear exactly once"
        );
        assert_eq!(sssd.matches("ldap_pwd_policy = none").count(), 1);
        assert!(sssd.contains("ignored_user_attributes"));

        let krb = fs::read_to_string(&paths.krb5_conf).unwrap();
        assert!(krb.contains("default_realm = TEST"));
        assert!(
            krb.contains("rdns = false"),
            "krb5.conf should include rdns=false for improved Kerberos reverse-DNS tolerance"
        );

        let main = fs::read_to_string(&paths.ganesha_conf).unwrap();
        assert!(main.contains("%include"));

        let exports: Vec<_> = fs::read_dir(&paths.exports_dir)
            .unwrap()
            .map(|e| e.unwrap().file_name())
            .collect();
        assert_eq!(exports.len(), 2);
        let frag =
            fs::read_to_string(paths.exports_dir.join("11-data.conf")).unwrap_or_else(|_| {
                let mut s = String::new();
                for e in fs::read_dir(&paths.exports_dir).unwrap() {
                    let p = e.unwrap().path();
                    if p.to_string_lossy().contains("data") {
                        s = fs::read_to_string(p).unwrap();
                    }
                }
                s
            });
        assert!(frag.contains("SecType = krb5i") || frag.contains("data"));
    }

    #[test]
    fn duplicate_names_rejected() {
        let mut c = minimal_cfg();
        c.shares.push(Share {
            name: "movies".into(),
            host_path: "/x".into(),
            ..Default::default()
        });
        assert!(c.validate_and_derive().is_err());
    }

    #[test]
    fn invalid_security_rejected() {
        let mut c = minimal_cfg();
        c.ganesha.default_security = "krb5x".into();
        assert!(c.validate_and_derive().is_err());

        let mut c2 = minimal_cfg();
        c2.shares[0].security = Some("aes-256".into());
        assert!(c2.validate_and_derive().is_err());
    }

    #[test]
    fn invalid_pref_read_rejected() {
        let mut c = minimal_cfg();
        c.shares[0].pref_read = Some(64 * 1024 * 1024 + 1);
        assert!(c.validate_and_derive().is_err(), "above max must be rejected");

        let mut c2 = minimal_cfg();
        c2.shares[0].pref_read = Some(1);
        assert!(c2.validate_and_derive().is_err(), "below min must be rejected");

        let mut c3 = minimal_cfg();
        c3.shares[0].pref_read = Some(16 * 1024 * 1024);
        assert!(c3.validate_and_derive().is_ok(), "valid 16M streaming value accepted");
    }

    #[test]
    fn load_host_paths_only_returns_only_host_paths() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("partial.conf");

        // Partial config (missing bind creds) — load_host_paths_only must still succeed.
        let partial = r#"
            ldap_uri = "ldaps://kllap.test:6360"
            [[shares]]
            name = "movies"
            host_path = "/media/SSD/movies"
            [[shares]]
            name = "backups"
            host_path = "/media/SSD/backups"
        "#;
        fs::write(&path, partial).unwrap();

        let roots = load_host_paths_only(&path).expect("should parse partial config");
        assert_eq!(roots.len(), 2);
        assert!(roots.iter().any(|p| p.to_string_lossy().contains("movies")));
        assert!(roots
            .iter()
            .any(|p| p.to_string_lossy().contains("backups")));
    }

    #[test]
    fn realm_is_required_no_silent_example() {
        let _env = ENV_LOCK.lock().unwrap();
        let _g1 = EnvGuard::remove("NFS_REALM");
        let _g2 = EnvGuard::remove("REALM");
        let mut c = NfsKlldapConfig {
            ldap_uri: "ldaps://kllap.example.com:6360".into(),
            kerberos: KerberosSection {
                realm: Some("EXAMPLE.COM".into()),
            },
            sssd: SssdSection {
                ldap_default_bind_dn: "uid=a,ou=people,dc=x,dc=com".into(),
                ldap_default_authtok: "s".into(),
                ..Default::default()
            },
            shares: vec![Share {
                name: "t".into(),
                host_path: "/t".into(),
                ..Default::default()
            }],
            ..Default::default()
        };
        let err = c.validate_and_derive().unwrap_err();
        let msg = err.to_string();
        assert!(msg.contains("kerberos.realm is required"));
        assert!(msg.contains("NFS_REALM"));

        // Good realm passes.
        c.kerberos.realm = Some("MY.REALM".into());
        assert!(c.validate_and_derive().is_ok());
        assert_eq!(c.effective_realm(), "MY.REALM");
    }

    #[test]
    fn realm_from_env_works() {
        let _env = ENV_LOCK.lock().unwrap();
        let _guard = EnvGuard::set("NFS_REALM", "ENV.REALM");

        let mut c = NfsKlldapConfig {
            ldap_uri: "ldaps://kllap.test:6360".into(),
            sssd: SssdSection {
                ldap_default_bind_dn: "uid=a,ou=people,dc=x,dc=com".into(),
                ldap_default_authtok: "s".into(),
                ..Default::default()
            },
            shares: vec![Share {
                name: "t".into(),
                host_path: "/t".into(),
                ..Default::default()
            }],
            ..Default::default()
        };
        assert!(c.validate_and_derive().is_ok());
        assert_eq!(c.effective_realm(), "ENV.REALM");
    }

    #[test]
    fn display_realm_returns_real_value_after_validation_and_placeholder_otherwise() {
        let _env = ENV_LOCK.lock().unwrap();
        let _g1 = EnvGuard::remove("NFS_REALM");
        let _g2 = EnvGuard::remove("REALM");
        let mut c = NfsKlldapConfig {
            ldap_uri: "ldaps://ldap.testdomain.com:6360".into(),
            sssd: SssdSection {
                ldap_default_bind_dn: "uid=admin,ou=people,dc=testdomain,dc=com".into(),
                ldap_default_authtok: "sekret".into(),
                ..Default::default()
            },
            shares: vec![Share {
                name: "t".into(),
                host_path: "/t".into(),
                ..Default::default()
            }],
            ..Default::default()
        };
        assert!(c.validate_and_derive().is_ok());
        assert_eq!(c.effective_realm(), "TESTDOMAIN.COM");
        assert_eq!(c.display_realm(), "TESTDOMAIN.COM");

        let mut broken = NfsKlldapConfig {
            ldap_uri: "ldaps://192.168.1.5:6360".into(),
            ..Default::default()
        };
        assert_eq!(broken.display_realm(), "YOUR.REALM");

        // EXAMPLE.COM treated as missing for display.
        broken.kerberos.realm = Some("EXAMPLE.COM".into());
        assert_eq!(broken.display_realm(), "YOUR.REALM");
    }

    #[test]
    fn sssd_tls_options_are_emitted_when_set() {
        let mut c = minimal_cfg();
        c.sssd.ldap_tls_reqcert = Some("never".into());
        c.sssd.ldap_id_use_start_tls = Some(true);
        c.sssd.ldap_tls_cacert = Some("/etc/pki/ca.crt".into());
        c.ldap_uri = "ldap://kllap.test:389".into();
        let _ = c.validate_and_derive();

        let tmp = tempfile::tempdir().unwrap();
        let paths = GenerationPaths {
            sssd_conf: tmp.path().join("sssd.conf"),
            krb5_conf: tmp.path().join("krb5.conf"),
            ganesha_conf: tmp.path().join("ganesha.conf"),
            exports_dir: tmp.path().join("exports.d"),
        };
        generate_all(&c, &paths).expect("generate with tls");

        let sssd = fs::read_to_string(&paths.sssd_conf).unwrap();
        assert!(sssd.contains("ldap_tls_reqcert = never"));
        assert!(sssd.to_lowercase().contains("ldap_id_use_start_tls = true"));
        assert!(sssd.contains("ldap_tls_cacert = /etc/pki/ca.crt"));
        assert!(sssd.contains("ldap_uri = ldap://kllap.test:389"));
    }

    #[test]
    fn kllldap_ignored_attributes_false_omits_ignore_blocks() {
        let mut c = minimal_cfg();
        c.sssd.kllldap_ignored_attributes = Some(false);
        let _ = c.validate_and_derive();

        let tmp = tempfile::tempdir().unwrap();
        let paths = GenerationPaths {
            sssd_conf: tmp.path().join("sssd.conf"),
            krb5_conf: tmp.path().join("krb5.conf"),
            ganesha_conf: tmp.path().join("ganesha.conf"),
            exports_dir: tmp.path().join("exports.d"),
        };
        generate_all(&c, &paths).expect("generate with kll=false");

        let sssd = fs::read_to_string(&paths.sssd_conf).unwrap();
        assert!(
            !sssd.contains("ignored_user_attributes"),
            "kll=false must not emit the KLLDAP ignore blocks into sssd.conf"
        );
        assert!(
            !sssd.contains("ignored_group_attributes"),
            "kll=false must not emit the KLLDAP ignore blocks into sssd.conf"
        );
        // Still emits the header note about the setting value
        assert!(sssd.contains("kllldap_ignored_attributes=false"));
    }

    #[test]
    fn ldap_uri_ip_rejected_with_exact_message() {
        let _env = ENV_LOCK.lock().unwrap();
        std::env::remove_var("NFS_REALM");
        std::env::remove_var("REALM");

        fn make_minimal(ip_uri: &str) -> NfsKlldapConfig {
            NfsKlldapConfig {
                ldap_uri: ip_uri.into(),
                sssd: SssdSection {
                    ldap_default_bind_dn: "uid=admin,ou=people,dc=x,dc=com".into(),
                    ldap_default_authtok: "s".into(),
                    ..Default::default()
                },
                shares: vec![Share {
                    name: "t".into(),
                    host_path: "/t".into(),
                    ..Default::default()
                }],
                ..Default::default()
            }
        }

        // IPv4
        let mut c = make_minimal("ldaps://192.168.10.5:6360");
        let err = c.validate_and_derive().unwrap_err();
        let msg = err.to_string();
        assert!(
            msg.contains(
                "LDAP IP addresses are not supported, DNS resolution is required for operation."
            ),
            "unexpected error: {}",
            msg
        );

        // IPv6 (with brackets in URI)
        let mut c6 = make_minimal("ldaps://[2001:db8::1]:6360");
        let err6 = c6.validate_and_derive().unwrap_err();
        assert!(err6
            .to_string()
            .contains("LDAP IP addresses are not supported"));

        // Also bare IPv6 without port etc.
        let mut c6b = make_minimal("ldap://[::1]");
        assert!(c6b.validate_and_derive().is_err());

        let mut ch = make_minimal("ldaps://kllap.example.com:6360");
        let hmsg = ch.validate_and_derive().unwrap_err().to_string();
        assert!(!hmsg.contains("IP addresses are not supported"));
        assert!(hmsg.contains("kerberos.realm is required"));
    }

    #[test]
    fn nfs_keytab_host_variants_short_and_fqdn() {
        assert_eq!(
            nfs_keytab_host_variants("aurora.testdomain.com"),
            vec!["aurora".to_string(), "aurora.testdomain.com".to_string()]
        );
        assert_eq!(nfs_keytab_host_variants("myserver"), vec!["myserver".to_string()]);
        assert_eq!(nfs_keytab_host_variants(""), Vec::<String>::new());
    }

    #[test]
    fn nfs_keytab_host_matches_short_or_fqdn() {
        assert!(nfs_keytab_host_matches("aurora", "aurora.testdomain.com"));
        assert!(nfs_keytab_host_matches("aurora.testdomain.com", "aurora"));
        assert!(!nfs_keytab_host_matches("other", "aurora.testdomain.com"));
    }

    #[test]
    fn docker_default_hostname_detection() {
        assert!(looks_like_docker_default_hostname("3c896c1c2e24"));
        assert!(looks_like_docker_default_hostname("a1b2c3d4e5f6"));
        assert!(looks_like_docker_default_hostname("0123456789abcdef"));
        assert!(!looks_like_docker_default_hostname("myhost.example.com"));
        assert!(!looks_like_docker_default_hostname("myhost"));
        assert!(!looks_like_docker_default_hostname("abc"));
        assert!(!looks_like_docker_default_hostname("3c896c1c2e24-nfs"));
    }

    #[test]
    fn derive_realm_from_uri_is_public_and_works() {
        assert_eq!(
            derive_realm_from_uri("ldaps://kllap.example.com:6360"),
            Some("EXAMPLE.COM".into())
        );
        assert_eq!(
            derive_realm_from_uri("ldap://sub.host.testdomain.local"),
            Some("HOST.TESTDOMAIN.LOCAL".into())
        );
        assert_eq!(derive_realm_from_uri(""), None);
    }
}
